- pvnet_app/app.py
A bug fix to compensate for the y-axis inversion in the nwp-consumer. 2 bugs = no bugs
> temp bug fix

- pvnet_app/app.py
- requirements.txt
This updates the summation model used.
The current summation model is a bit noisy. In our forecasts there are some high frequency perturbations from a smooth curve which I do not believe are indicative of model skill, but more the model being overly sensitive to the inputs. Although the accuracy of the model is good, I think it makes us look bad from a user's perspective - can we trust an accurate but wobbly line? These high frequency deviations would also likely make our forecasts worse as measured by ramp-rate. 
This new model is trained with more effective regularisation (due to rescaling the inputs), and is trained for longer using a slower changing learning rate. This results in smoother forecasts, and a very modest improvement in validation scores.
Both the new and old model were …
> Update summation model to reduce wobbles

- pvnet_app/app.py
- tests/test_app.py
This saves the sum-of-GSPs under a different model name to the logging. This will allow us to compare the performance of the summation model to the simpler sum-of-GSPs, and help us monitor the summation model's performance more easily.
This is part of #15. 
Includes:
- Optional saving of the sum-of-GSPs using the environmental variable `SAVE_GSP_SUM` (default: False)
- If saved the sum-of-GSPs is saved under the model name `pvnet_gsp_sum`
- Updated tests
> add optional sum-of-GSP saving

- pvnet_app/app.py
PVNet on dev is currently failing due to the NWP data in production having both OSGB and lat-lon coordinates. This is just an hot fix until I can make the appropriate (larger) changes in datapipes
> hot fix for multiple spatial coords

- pvnet_app/app.py
Add properties to the forecast only when they are not null. Stops us uploading an empty dict. This is mainly for `pvnet_sum_gsps`.
> Add properties only when not empty

- pvnet_app/app.py
- pvnet_app/consts.py
- pvnet_app/data.py
- pvnet_app/utils.py
- requirements.txt
- tests/test_app.py
Update to remove torchdata. Similar to openclimatefix/PVNet#95
> Pytorch datapipes

- pvnet_app/app.py
- pvnet_app/consts.py
- pvnet_app/data.py
- requirements.txt
- tests/conftest.py
- tests/test_app.py
Currently the logic for switching between 5/15 minutely satellite data is contained inside datapipes. I think its cleaner to have this logic inside this app as it is exclusive to production code. It also stops us having more if/else clauses in the pvnet datapipe for training/production and makes the datapipe more straight forward and maintainable.
Also having it here gives us the opportunity to maybe combine or infill between the 5 and 15-minutely data as well as having more targeted logging.
> add 5/15 sat logic

- requirements.txt
use nowcasting_datamodel 1.5.30. This restricts the adjust to 20% of the forecast value amount
Fixes #
CI tests
> nowcasting_datamodel>=1.5.30

- pvnet_app/app.py
Replace the model weights. Some of the weights had remained in their initialised states, not trained states, in the previous model
> fix model weights

- .bumpversion.cfg
Update version.
Once the pvnet model has been updated to represent the forecast sent in backtest, this should be changed to 2.1.
Forecast sent in backtest was UK national probabilistic with ensembles and ECMWF.
> update version to 2.0.1

- pvnet_app/app.py
Replace model with one which uses 60 minute satellite delay. This is needed to debug the cause of poor performance in live environment at short time horizons
> replace model with higher satelite delay

- pvnet_app/app.py
- pvnet_app/forecast_compiler.py
- requirements.txt
- scripts/cache_default_models.py
- tests/conftest.py
- tests/test_app.py
- tests/test_data.py
As part of our development cycle, it is beneficial to be able to run multiple versions of on dev at once. This pull requests adds the option for the app to be able to run multiple PVNet models. 
This is configurable with the `RUN_EXTRA_MODELS` environmental variable so the extra models will not be run on prod.
Extra things to consider:
- Naming conventions for the extra models. With lots of extra models we might end up with lots of models to choose between on the dashboard
- Dashboard needs to be updated to show these models
> Add option to run multiple models

- pvnet_app/app.py
- requirements.txt
- tests/test_app.py
Dont save extra models gsp values to last seven days forecast value table
#93 
> an option to not save gsp data to forecast_value_last_seven_days

- pvnet_app/app.py
An issue occurred in creating the v9 batches where the UKV channels were rearranged into alphabetical order. This meant when training the model was given the UKV channels in alphabetical order but live we were feeding them in in the order they appeared in the data config. 
This pull request updates all the models using UKV so the data config used live has the UKV channels in alphabetical order and thus aligns train and production
Also added back in some of the models with different levels of satellite delay
> Fix UKV channel permutation

- pvnet_app/app.py
- Adding summation model for PVNet day ahead
- Small change to allow local predictions from pvnet day ahead model
Unit tests passed locally (although some tests were only passing when reducing number of workers) and ran the app locally which gave sensible outputs
> Add day ahead summation model

- pvnet_app/app.py
This replaces the default model (which used 60 minutes of satellite delay) with one which uses 30 minutes of satellite delay
> Replace default model

- pvnet_app/data.py
- tests/conftest.py
- tests/test_data.py
- tests/test_data/test.yaml
Fix why satellite data wasnt checked
The fix is to use `hasattr` not `in`
Small code that shows bug
```
from pvnet.models.base_model import BaseModel as PVNetBaseModel
from ocf_datapipes.config.load import load_yaml_configuration
name = "openclimatefix/pvnet_uk_region"
version = "aa73cdafd1db8df3c8b7f5ecfdb160989e7639ac"
data_config_filename = PVNetBaseModel.get_data_config(name, version)
data_config = load_yaml_configuration(data_config_filename)
assert "satellite" in data_config.input_data # this doesnt work
assert hasattr(data_config.input_data, "satellite") # this does
```
Added a test and checked it failed with old code
> fix for satellite check

- pvnet_app/data/satellite.py
- tests/data/test_satellite.py
Only fill in the last 3 hours of satellite data. This is to stop large infills of data, that can cause memory errors
Helps with #135 
CI tests + new tests
> Only infill last 3 hours #135

- pvnet_app/model_configs/all_models.yaml
Make pvnet ecmwf name simple.
This make it easier with blending
Helps with #123 
CI tests
> make pvnet ecmwf only name simple

- pvnet_app/app.py
- pvnet_app/model_configs/all_models.yaml
- pvnet_app/model_configs/pydantic_models.py
- tests/model_configs/test_pydantic_models.py
- tests/test_app.py
- add back in old pvnet model 
- add back in old pvnet ecmwf model
- add option to switch from models using ocf_data_sampler and ocf_datapipes
- added new test in
As there are code changes since 2.3.30 the old version, it would be great to run the models with no ocf_data_sampler on dev for a bit, just to check they are working similar to production
Helps withs #123 
CI tests
> add back in pvnet ecmwf old model

- pvnet_app/data/satellite.py
- tests/conftest.py
- tests/data/test_satellite.py
Check satellite data for zeros
#149 
CI tests
> add check for corrupt satellite data

- pvnet_app/consts.py
- pvnet_app/data/satellite.py
- tests/data/test_satellite.py
- Raise error if there are any nans in the satellite data
- This reuses some code, for checking for zeros
#158 
Ci tests
> No satellite nans

- pvnet_app/data/nwp.py
Fixes for new ECMWF data
Helps with https://github.com/openclimatefix/ocf-infrastructure/issues/697
> remove nans in nwp

- pvnet_app/forecast_compiler.py
Make sure there are no nans in the gsp capacites
This doesnt solve the underlying issue, but at least it will catch the problem
CI tests
> check for nans in gsp capacities

- pvnet_app/forecast_compiler.py
- tests/conftest.py
Add a hard limit, so if the maximum of the forecast is above 10% of the national capacity, dont let the forecast be fail, and let the app fail. 
#174 
Ci tests
> Add hard max limit

- README.md
Added a description of what checks are in place 
#213 
Ci tests, but just in readme
> add which checks are in place in readme

- README.md
- src/pvnet_app/validate_forecast.py
- tests/test_validate_forecast.py
Adjust zig zag validation. Change from `up,down` to `up,down,up`. This is because this is sometimes we get up,down as normal solar forecast behaviour
CI tests
> zig-zag-zig

- tests/conftest.py
- tests/data/test_satellite.py
- tests/test_app.py
- tests/test_app_legacy.py
- tests/test_datalaoder.py
This PR improves on the use of pytest fixtures within our tests. Some of the DataArray fixtures are moved to be sessioned scoped since we use them multiple times. The main change is around the database fixture. This PR makes the database be created and populated once with input data. After each test that uses it, all of the forecast values are deleted from the database again. This should be more efficient than what we do now - to create a new database for each test
This supersedes #153
> clean up test database fixtures

- src/pvnet_app/app.py
- src/pvnet_app/consts.py
- src/pvnet_app/model_configs/all_models.yaml
- src/pvnet_app/model_configs/pydantic_models.py
This makes a few of the changes from #255 
- Add function for getting boolean env variables
- Lay out the model config better
- Also change some of the names of the extra model. I believe these names are now out of date
- None of the actual model have been changed
- Strip back the model config to remove unnecessary bits
- Remove unneeded nested try-except block
- Move to pandas datetimes
- Fix type hinting where misleading / wrong
- Get rid of unused UK sat bounding box
- Other minor changes
> Refector stage 1

- README.md
- src/pvnet_app/app.py
- src/pvnet_app/dataloader.py
- src/pvnet_app/forecast_compiler.py
- tests/test_app_legacy.py
- tests/test_datalaoder.py
This is another part of the refactor.
- Move batch device handling and torch.no_grad into the forecast compiler
- Clean up the dataloaders and switching between the datapipes and data-sampler versions
- Clean up some of the logging set up
- Remove `PVNET_V2_VERSION` and `PVNET_V2_SUMMATION_VERSION` from docstrings as these aren't actually used anymore
- Reorder some of the `app()` function setup
> partial refactor

- tests/test_app_legacy.py
Previously in this test module, the ECMWF-only model was actually using the ocf-data-sampler version. I think the intended behaviour is that all tests in this module use the ocf_datapipes versions
> fix legacy ecmwf model used

- src/pvnet_app/data/satellite.py
Fixes the `get_pvnet_satellite_spatial_bounds()` function which had a couple of small bugs. 
- Poor choice in initialisation values
- Typos
I tested this locally to see which are of the current live satellite would be selected. The area is shown in the image below.
> Hot fix get_pvnet_satellite_spatial_bounds

- pyproject.toml
Update to nowcasting_datamodel==1.7.2. This helps with 
Helps with https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/459
> nowcasting_datamodel==1.7.2

- README.md
- src/pvnet_app/app.py
- src/pvnet_app/data/satellite.py
- tests/data/test_satellite.py
- 15 minute satellite can be set with seperate path compared to 5 minute satellite data. Default behaviour is still the same
- https://github.com/openclimatefix/uk-pvnet-app/issues/330
- This is needed for https://github.com/openclimatefix/airflow-dags/issues/145
- added a test
> add option for 15 minute satellite

- pyproject.toml
- src/pvnet_app/forecaster.py
- src/pvnet_app/model_configs/all_models.yaml
- tests/test_app.py
Upgrades the app to use pvnet 5.0.3 and pvnet-summation 1.0.0
I've updated the huggingface commits , but the models being run are the exact same. I just updated them with the migration scripts in pvnet and pvnet-summation  so they can run with the updated packages
> Update PVNet + summation model

- src/pvnet_app/model_configs/all_models.yaml
- tests/model_configs/test_pydantic_models.py
Add a new PVNet intraday model which uses 2NWP + satellite with a 0-minute delay
> Add model with 2NWP and 0-min sat delay
