openclimatefix/uk-pvnet-app

- requirements.txt
> cpu torch only

- configs/data_configuration.yaml
- pvnet_app/app.py
- requirements.txt
Download nwp at the start, might help with https://github.com/openclimatefix/PVNet/issues/83
CI test
> download nwp data at the start

- pvnet_app/app.py
Remove the flip added in #10  which will be fixed in the NWP consumer
> Remove NWP y-axis flip

- pvnet_app/app.py
This reduces the RAM usage for the regridding by performing it iteratively for each step rather than in parallel as before
> Regrid more RAM efficiently

- pvnet_app/app.py
- requirements.txt
_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._
Fixes #
> Update nowcasting datamodel

- pvnet_app/app.py
- pvnet_app/utils.py
- requirements.txt
Update to datapipes v3
The model commits have changed but the underlying trained models for both PVNet and the summation model are the same - i.e. the same model weights
> Update to datapipes v3

- Dockerfile
- requirements.txt
> Add unzip to dockerfile

- pvnet_app/app.py
- requirements.txt
- update ocf_datapipes
- pin torch
- update pvnet version (due to fields changing in configuration)
CI tests
> Update ocf datapipes

- pvnet_app/app.py
Add more logging
Fixes #
CI tests
> add more logging

- pvnet_app/app.py
- pvnet_app/data.py
Fix for loading 15 minute satellite data
- CI tests
- ran it locally
> fix for 15 minute satellite data

- requirements.txt
Update ocf datapipes which fix sun elevation bug
CI tests and ran locally
> ocf_datapipes==3.2.7

- requirements.txt
stick wiht pytorch-ligthning==2.1.3
Might fix #44 but having trouble testing locally
CI tests
> Bug torchvision nms

- Dockerfile
Keep docker torch on cpu
Fixes #
CI tests,
> pin to torch 2.2.0 in docker

- pvnet_app/data.py
Convert to the UKV data to float16 to align with training
> Convert UKV to float16

- pvnet_app/app.py
Replace UMT model with a freshly trained multimodal model
> replace model

- pvnet_app/utils.py
Fix the variable name used when the output is not probabilistic
> Wrong variable name

- pvnet_app/app.py
- pvnet_app/data.py
Declutter the logging by filtering out more the sqlalchemy stuff which dominates the logs
> Declutter logging

- pvnet_app/data.py
_This is my commit to solve the good first issue of Open Climate Fix: Improving the loggin of the delay so it show in minutes._
Fixes #
_Modification in: data.py so the timedelta is not directly referenced in the loggin print._
> Adding my take on the good first issue for improving the delay loggin

- pvnet_app/app.py
Update the summation model to one which has been trained on the outputs of the current PVNet model
> update summation model

- pvnet_app/app.py
- pvnet_app/data.py
- requirements.txt
- tests/conftest.py
- tests/test_data.py
- Update model to newly trained model with 0 minute-delay
- Update data processing to fill in missing timestamps with NaNs but only up to limit that model was trained with
- Update tests
- Cleaning and refactoring
- Update dependencies
> Update app to use model which uses less satellite delay

- requirements.txt
Update nowcasting_datamodel>=1.5.41
CI test
> nowcasting_datamodel>=1.5.41

- pvnet_app/app.py
- pvnet_app/utils.py
Add some logic to find the minimum satellite delay needed by the models being run
> find min sat delay across models

- pvnet_app/app.py
Replace pvnet model with the new 60 minute model
> Replace pvnet model

- pvnet_app/app.py
The database has slowed down a lot recently and I'm wondering if it can't handle many models
> Remove some extra models

- pvnet_app/app.py
Updating the day ahead summation model version
> Update day ahead summation model

- pvnet_app/app.py
Use adjuster in pvnet day ahead models
> Use adjuster for pvnet day ahead

- pvnet_app/data.py
Add logging for satellite delay, and where nwp data is being downloaded from
CI tests
> add nwp and satellite logging

- pvnet_app/app.py
- pvnet_app/data.py
- test-docker-compose.yml
- tests/conftest.py
- tests/test_data.py
- make sure all satellite data is there
- some formatting changes in there too
Helps with #104 
CI tests
> checking satellite data

- Dockerfile
Bump docker to python3.12
Might help with #111 
CI tests
> pytnon3.12

- Dockerfile
- requirements.txt
use torch 2.3.1 and use conda forge to install torch vision
Helps with #111 
CIT test+ tested locally
> torch 2.3.1 and use conda forge to install

- pvnet_app/app.py
Have option to not download satellite data
Fixes #
CI tests
> option to not download satellite data

- pvnet_app/app.py
- pvnet_app/data/satellite.py
- pvnet_app/dataloader.py
- pvnet_app/utils.py
- Replace the dropout values in the data configs before running
- Also add missing docstrings and type hints
Potentially fixes #129
> Config dropout

- pvnet_app/app.py
A minor sentry update to the existing codebase, so as to have a uniform pattern throughout our repos
A continuation to: https://github.com/openclimatefix/ocf-infrastructure/issues/540
> Minor sentry update to the existing code

- pvnet_app/app.py
- pvnet_app/forecast_compiler.py
- pvnet_app/model_configs/all_models.yaml
- pvnet_app/model_configs/pydantic_models.py
- tests/conftest.py
- tests/model_configs/test_pydantic_models.py
- tests/test_app.py
- switch to use pydantic models
- have easy option to only use ecmwf model `USE_ECMWF_ONLY`
Fixes #96 
CI tests
> switch to pydantic models + ECMWF only model

- pvnet_app/data/satellite.py
If sate en variable has not be set, then dont try to download it
Helps with #123 
CI tests
> No satellite download

- pvnet_app/app.py
- pvnet_app/data/nwp.py
- Dont download UKV data, if only using ECMWF model
Helps with #123 
CI tests
> Only download UKV if needed

- pvnet_app/app.py
> change ~ to not

- pvnet_app/app.py
Make the logging set up a bit simplier
Might help make sentry errors come through
CI tests
> simplify logging

- pvnet_app/model_configs/all_models.yaml
- tests/test_app.py
use correct ECMWF only model
Fixes #151 
CI tests
> fix to use ecmwf model only

- pvnet_app/data/nwp.py
Optional rename of ECMWF variable
Helps with #160 
CI tests
> rename ECMWF dataset variable

- pvnet_app/data/nwp.py
Rename new nwp consumer variables
This is needed for https://github.com/openclimatefix/ocf-infrastructure/issues/697
> rename new nwp variables to old ones

- pvnet_app/app.py
_Resolved the error of file not being saved locally_
> fix (batches): saving the batches

- pvnet_app/model_configs/all_models.yaml
- pvnet_app/model_configs/pydantic_models.py
- tests/test_app.py
Minimal updates pushed - pydantic_models update regarding ModelHF to enable current specification of summation model being none - hope this is OK as of the moment. Full working order.
Not immediate , but regarding potential refactor for dynamic config handling in terms of compatibility, would definitely like to pick this up pending full migration to data-sampler if possible. Made some progress here - yet a few further changes required.
> DA model update

- .github/workflows/conda-pytest.yaml
- requirements.txt
- pin python to 3.12 in pytest CI
Fixes #181 
CI tests
> Fix CI pytests

- .bumpversion.cfg
- .github/workflows/conda-pytest.yaml
- pvnet_app/__init__.py
- pvnet_app/dataloader.py
- requirements.txt
_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._
Fixes #
> ensuring tests pass

- requirements.txt
Update ocf-datapipes, more robust for no PVLive data
CI tests
> ocf_datapipes==3.3.57

- pvnet_app/data/nwp.py
New variable names are lower case, so need to account for this
Helps this https://github.com/openclimatefix/nwp-consumer/issues/238
CI tests
> small upgrade for ecmwf namings

- pvnet_app/forecast_compiler.py
Make sure forecast deosnt run if ECMWF data is all zeros
#194 
CI tests
> validate nwp data source

- src/pvnet_app/data/satellite.py
- tests/data/test_satellite.py
There was a bug in the timestep interpolation method such that it wasn't filtering out timestamps beyond the max gap size when it is infilling. This fixes the issue and adds a test for it
> interpolation max_gap fix

- src/pvnet_app/model_configs/all_models.yaml
- tests/test_app.py
Updated regarding newly trained PVNet2 intraday models
> Intraday update

- src/pvnet_app/app.py
- src/pvnet_app/data/gsp.py
This PR refactors the GSP capacity loading code into a separate function for better code organization.
Changes:
- Created new data/gsp.py file with dedicated function for loading capacities
- Moved GSP and national capacity loading logic to new function
- Updated app.py to use the new function
Fixes #205
> refactor: move GSP capacity loading to separate function (#205)

- .github/workflows/main_ci.yml
After discussion with @peterdudfield, modifying the bump and build CI to run on pushes to main. Addresses #217
> feat(ci): Change merged-ci to run on main push

- src/pvnet_app/app.py
This commit refactors the batch saving logic within the app function into a separate function called save_batch_to_s3. This improves the readability and modularity of the app function. The original batch saving code block is removed, and the new function is called in its place.
This change makes the code more maintainable and allows for potential reuse of the batch saving logic in other parts of the application. The function call that the original code was replaced with is save_batch_to_s3(batch, model_name, s3_directory).
Fixes #204
> Refactor: Extract batch saving to save_batch_to_s3

- src/pvnet_app/data/satellite.py
- tests/data/test_satellite.py
> fix for checking nans, add tests too

- README.md
> Environment variables added

- Dockerfile
- src/pvnet_app/app.py
> fix(Dockerfile): Correct version in docker container

- src/pvnet_app/model_configs/all_models.yaml
Updated for all trained Intraday models - correct Sat pre-processing
> Update all_models.yaml - Intraday models updated - ALL

- src/pvnet_app/model_configs/all_models.yaml
Summation updated for all sources - sat 30 min delay
> Update all_models.yaml - All (30 min sat delay - intraday)

- src/pvnet_app/model_configs/all_models.yaml
Summation updated for single source - ecmwf only
> Update all_models.yaml - ecmwf only (intraday)

- src/pvnet_app/model_configs/all_models.yaml
Summation updated for single source - sat only
> Update all_models.yaml - sat only (intraday)

- src/pvnet_app/model_configs/all_models.yaml
Reduced quantile range and regularisation inclusion
> Summation da update

- src/pvnet_app/app.py
- src/pvnet_app/data/nwp.py
- src/pvnet_app/data/satellite.py
- src/pvnet_app/model_configs/pydantic_models.py
- tests/data/test_satellite.py
- tests/test_app.py
- tests/test_app_legacy.py
Part 4 of the refactor in #255
The main piece of this PR is to refactor the satellite download logic. I have moved it into a class to match the structure of the NWP download class. This also changes the behaviour of the satellite quality checks. Before, if the satellite data was not okay, the app would crash. Now if the satellite data is not okay, the app treats this as if the satellite data is not available. The app still tries to run whatever models can be run without satellite data 
Also
- Move accessing the satellite path env vars into the main app function
- Add clean up to the downloaders so that the input data is deleted after running the forecast
> Refactor: stage 4

- README.md
- src/pvnet_app/app.py
- src/pvnet_app/model_configs/all_models.yaml
- src/pvnet_app/validate_forecast.py
- tests/test_app.py
- tests/test_app_legacy.py
- tests/test_forecast_compiler.py
- tests/test_validate_forecast.py
This just merges the changes from main into the refactoring branch
> Refactor 6: merge

- README.md
- src/pvnet_app/app.py
- src/pvnet_app/config.py
- src/pvnet_app/data/batch_validation.py
- src/pvnet_app/data/gsp.py
- src/pvnet_app/data/nwp.py
- src/pvnet_app/data/satellite.py
- src/pvnet_app/dataloader.py
- src/pvnet_app/forecast_compiler.py
- src/pvnet_app/model_configs/all_models.yaml
- src/pvnet_app/model_configs/pydantic_models.py
- src/pvnet_app/utils.py
- tests/data/test_satellite.py
- tests/model_configs/test_pydantic_models.py
- tests/test_app.py
- tests/test_app_legacy.py
- tests/test_datalaoder.py
- tests/test_forecast_compiler.py
- tests/test_validate_forecast.py
This is the last piece if the refactor from #255 
This PR is mainly cosmetic changes
- Change env var `FORECAST_VALIDATION_SUN_ELEVATION_LOWER_LIMIT` to `FORECAST_VALIDATE_SUN_ELEVATION_LOWER_LIMIT` to better match pattern of other env vars
- Move 2 funcs from app to utils
- Some light refactoring of a few functions
- Doc strings
> Refactor: stage 7

- pyproject.toml
- tests/conftest.py
- Update the entry point. This fixes #277 
- Also remove session scoping from database fixtures. These seem to not be reliably reset between tests
I have run the docker container locally. It got past the failure point in #277
> update entry point

- src/pvnet_app/data/nwp.py
- rename data variables
- rename weather variables
- make sure it has the correct variables before regridding
https://github.com/openclimatefix/nwp-consumer/pull/226
Nwp data after processing looks like this
> rename ukv for new nwp-consumer

- src/pvnet_app/data/nwp.py
> remove compute

- src/pvnet_app/utils.py
Add to log message, to show which forecasts were completed
#291
> add which forecasts were sucessful

- README.md
- src/pvnet_app/data/nwp.py
Check the NWP for NaN values before processing. NWP is treated as not available if it contains NaNs.
> Add NWP NaN checks

- pyproject.toml
- fix version, not not show dirty
- this was happening becasue not all git files are copied to docker file, so it think there are some unstashed changes. Another option is to copy all those files to docker. 
#67 
Not been tested
> just show tag in version

- src/pvnet_app/app.py
Bump to new version, 2.5.17 was duplicated in database, was tricky to work with
Only changed a comment
> small comment update

- src/pvnet_app/app.py
- src/pvnet_app/data/nwp.py
- tests/conftest.py
Dont regrid ECMWF data when running DA model
I had to add in .compute when not regridding. This is because when saving, the whole zarrs went to nans - I dont really understand why
#315
> add regrid option for ECWMF

- pyproject.toml
_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._
Fixes #
> Bump ocf_datapipes version

- README.md
- src/pvnet_app/data/satellite.py
Option for not scalling satellite data
#328 
-  CI tests
> add option for SATELLITE_SCALE_FACTOR

- src/pvnet_app/app.py
use pvnet improt not src.pvnet
Ci tests
> fix import

- src/pvnet_app/data/satellite.py
make sure satellite area attrs is yaml
Helps with new satellite data
> make sure attrs area is yaml
